### PR TITLE
fixes #5685 - Quick fix for ViconFastBale stopping

### LINKED ISSUE #5685: Kverneland/Vicon FastBale stoppt beim Ballenauswurf zum Wickler
Hallo,
besten Dank erst mal für eure tolle Arbeit.
Ich verwende die FastBale Rundballenpresse/Wickelkombi aus dem Kverneland DLC. Der Vorteil dieser Presse ist die Verwendung zweier Presskammern, somit muss diese Presse nicht mehr anhalten um den Ballen an den Wickler zu übergeben. Leider funktioniert das mit CP noch nicht, wenn die Hauptkammer 100% Füllstand erreicht stoppt CP das Gespann bis die Hauptkammer entladen ist. Somit geht der Vorteil des schnelleren Arbeitens leider verloren bzw. aufgrund der schon geringeren Arbeitsgeschwindigkeit dieser Presse dauert das Pressen mit CP unnötig lange.
Es wäre Toll, wenn Ihr das so hinbekommen könntet dass CP nur noch stoppen würde wenn Vor- und Hauptkammer 100% erreicht haben sollten (Falls die Ballenübergabe noch nicht beendet wäre wenn die Vorkammer bereits wieder 100% erreicht hat, bei grosser Schwade).

### PR DESCRIPTION
**Pull request by ddewar**
This is a quick fix for the Vicon Fast Bale stopping. Ideally, finding a specialization for this kind of baler and ignoring the stop logic would be best, but I could not find out easily. Only real change I have noticed is non-fast balers will move forward a few inches after unloading. This does not result in any missed swath. Fixes #5685

### CODE REVIEW

File: BalerAIDriver.lua [hunk 1]
```diff
@@ -71,8 +71,11 @@ function BalerAIDriver:handleBaler()
 					self.baler:setIsUnloadingBale(true, false)
 				end
 			elseif self.baler.spec_baler.unloadingState ~= Baler.UNLOADING_CLOSED then
-				allowedToDrive = false
-				if self.baler.spec_baler.unloadingState == Baler.UNLOADING_OPEN then
+				if fillLevel >= capacity then -- Only stop if capacity is full. Allowing for continuous balers such as the ViconFastBale
+					allowedToDrive = false
+				elseif fillLevel == 0 and self.baler.spec_baler.unloadingState == Baler.UNLOADING_CLOSING then
```
Comment (ddewar) [inline BalerAIDriver.lua:76]: This check was added. Without it, the baler would miss small parts of the swath while the chamber is closing.
