### PR TITLE
Diff fixes

### LINKED ISSUE #6611: Mode 3 : Overloader does not brake at the overload point (to high speed when approach waitpoint ?)
Good day! Apologies for my english, using google translate. When using 3 modes, the tractor passes the unloading point without braking, but simply coasting, so it will responsibly drive away from the reloading point. Attaching photo.

### LINKED ISSUE #6810: Mode 3 Save pipe position
Hi Guys
Using the latest version (.38), just wondering was the option to save pipe position removed from the specific tool page for mode three overloaders? If it has been, has it been by mistake?

fsScreen_2021_02_11_00_53_13

Thanks guys
G

### LINKED ISSUE #7051: Question: Shovel Mode
I use this mode with a "Radlader" in the BGA with out any problems. I did exact the same thing for the manure at the cow pasture, from the documentation it should work, but it doesn't. The filling of the shovel works like a charm, but it doesen't do the unloading. What is diffrent to the BGA? I use a "Teleskiplader" instead of a "Radlader" and there is no trigger. But in both cases I don't use triggers, instead i use the parking position.

Any ideas? I couldn't get it to work just by reading the documentation.

### PR DESCRIPTION
**Pull request by schwiti6190**
- small action event improvements.
- added a global setting to disable action event texts.
- fixes #7051,  fixes #6810,  fixes #6611
- added the possibility to print variables to drifferent xml files
- added printGlobalCpVariable()

### CODE REVIEW

File: ActionEventsLoader.lua [hunk 1]
```diff
@@ -323,6 +328,12 @@ function ActionEventsLoaderUtil.getActionEventText(actionEventData)
 	return actionEventData.text or ActionEventsLoader.textPrefix..actionEventData.name
 end
 
+---Needs the action event text to be visible?
+---@param table actionEventData from the config xml
+function ActionEventsLoaderUtil.isActionEventTextVisible(actionEventData)
+	return courseplay.globalSettings.showActionEventsTexts:get() or actionEventData.textVisibilityNeeded
```
Comment (pvaiko) [inline ActionEventsLoader.lua:334]: would `textAlwaysVisible` describe `textVisibilityNeeded` better what it is for?

File: base.lua [hunk 2]
```diff
@@ -585,6 +585,16 @@ function courseplay:onUpdate(dt)
 		self.cp.infoText = nil
 	end
 
+	if self.cp.firstRun == nil then 
+		if self.cp.driver then 
+			---Post init function, as not all giants variables are
+			---set correctly at the first courseplay:setAIDriver() call.
+			self.cp.driver:postInit()
+			self.cp.firstRun = true
```
Comment (pvaiko) [inline base.lua:593]: This is confusing, if firstRun is true, I'd think it is the first run, but the opposite seems to be the case. I'd recommend renaming it to `postInitDone` or something more descriptive.

File: config/ActionEventsConfig.xml [hunk 3]
```diff
@@ -16,6 +16,7 @@
 			isDisabledCallbackFunc: is used to disable a action event after a action event refresh or on load.
 			callbackState: isDisabledCallbackFunc parameter, this is an int!
 			text: is the action event text, by default it returns courseplay:loc(name), where 'name' is the previous defined action event name.
+			textVisibilityNeeded: Is disabling action event text forbidden ? (default: false)
```
Comment (pvaiko) [inline config/ActionEventsConfig.xml:19]: very confusing description (maybe it is due to my age :) but disabling forbidden is false is just too much boolean logic for me...

**Review by pvaiko — APPROVED** [review]
