### PR TITLE
A few Setting reworked and diff fixes

### LINKED ISSUE #6402: WE ask YOU: Question about Waitpoint and Wait Time use
Hello Community,

we often read Issues and Questions about the waittime in few Modes and we ask ourself, what are you guys use it for?

What comes up in our mind is:
- Trafficcontrol: Delaying some Drivers to not crash into each other, wich should be mostly solved with our TrafficController introduced in 6.03.xxxx1 and higher
- Mode1: Wait under a conveyor belt to load something, wich should just work fine when you set a min value what you want to load (or even just stay under it)

So we don't rly see a need of this, so we would like to know, what you use it for and is this rly a needed feature.

Greetings,
Dev. Team

### PR DESCRIPTION
**Pull request by schwiti6190**
- 2 LoadUnloadOffset settings
- 2 CombineOffset settings (old combineOffset and tipperOffset)
- WaitTime setting #6402
- Alignment setting removed.

- Wait time fixes #6402
- Added visible search radius on change mode 10
- Diff fuel save improvements #3933 #7075

### CODE REVIEW

File: CombineUnloadAIDriver.lua [hunk 1]
```diff
@@ -740,7 +741,7 @@ end
 ---@return number, number x and z offset of the pipe's end from the combine's root node in the Giants coordinate system
 ---(x > 0 left, z > 0 forward) corrected with the manual offset settings
 function CombineUnloadAIDriver:getPipeOffset(combine)
-	return combine.cp.driver:getPipeOffset(-self.vehicle.cp.combineOffset, self.vehicle.cp.tipperOffset)
+	return combine.cp.driver:getPipeOffset(-self.settings.combineOffsetX:get(), self.settings.combineOffsetZ:get())
```
Comment (pvaiko) [inline CombineUnloadAIDriver.lua:744]: Not sure how exactly this works now but this would probably be a good time to flip the sign of the offset settings. Now that it is called X, it should have the same sign as the engine's x coordinate (left and forward positive). 

If it is the opposite, then it should be called combineOffsetRight or combineRightOffset, declaring that if the number is positive, the offset is to the right.

File: base.lua [hunk 2]
```diff
@@ -1080,30 +1026,22 @@ function courseplay:saveToXMLFile(xmlFile, key, usedModNames)
...
-	setXMLString(xmlFile, newKey..".combi #combineOffsetAutoMode", tostring(self.cp.combineOffsetAutoMode))
 	
 	--driving settings
 	setXMLInt(xmlFile, newKey..".driving #turnDiameter", self.cp.turnDiameter)
 	setXMLBool(xmlFile, newKey..".driving #turnDiameterAutoMode", self.cp.turnDiameterAutoMode)
-	setXMLString(xmlFile, newKey..".driving #alignment", tostring(self.cp.alignment.enabled))
 	
 	--field work settings
-	local offsetData = string.format('%.1f;%.1f;%.1f;%s;%.1f;%.1f;%d', self.cp.laneOffset, 0, 0, 0, self.cp.loadUnloadOffsetX, self.cp.loadUnloadOffsetZ, self.cp.laneNumber);
+	local offsetData = string.format('%.1f;%.1f;%.1f;%s;%.1f;%.1f;%d', self.cp.laneOffset, 0, 0, 0, 0, 0, self.cp.laneNumber);
```
Comment (pvaiko) [inline base.lua:1041]: Do we still need this, the settings are saved in the XML anyway, right?

**Review by pvaiko — CHANGES_REQUESTED** [review]
Great job on the hold/wait. Just a few minor things to check.

File: CombineUnloadAIDriver.lua (hunk 1 above)
Comment (Tensuko) [reply CombineUnloadAIDriver.lua:744]: The text on the HUD shows left/right/front/back now.
But I will check on Combine with the pipe on the right side, if it gets flipped.

Comment (Tensuko) [reply CombineUnloadAIDriver.lua:744]: @schwiti6190 yes, they are correct.

File: base.lua (hunk 2 above)
Comment (pvaiko) [reply base.lua:1041]: makes sense

File: CombineUnloadAIDriver.lua (hunk 1 above)
Comment (pvaiko) [reply CombineUnloadAIDriver.lua:744]: I was talking about the naming of the variables only, especially the side offset, calling it RightOffset would make clear that right is > 0 (contrary to the X coordinate in the Giants engine, which is > 0 to the left)
