### PR TITLE
Some MP, mode9 and baler improvements

### LINKED ISSUE #5701: Offloader Wont Find Combine (Dedicated Server)
Hello, my offloader is not locating any combines when using courseplay. They sit at the waiting area with their lights going without moving. 

Image from offloader:
https://gyazo.com/1348e486875d93a5dfda1792a564ff6c

Imagefrom combine:
https://gyazo.com/98927b2d9c2eec390840ccb1153c02fb

Game log file pastebin:
https://pastebin.com/aNvryDAj

Server log file pastebin:
https://pastebin.com/RYJPVzNH

### LINKED ISSUE #6167: Error: Running LUA method 'mouseEvent' - CpManager.lua:196: bad argument #1 to 'pairs' (table expected, got nil)
Hallo wir bekommen diesen Fehler beim betreten des Server
[log.txt](https://github.com/Courseplay/courseplay/files/5322244/log.txt)
Hoffe ihr könnt mir helfen
Gruß

### LINKED ISSUE #6213: Dedicated Server Lua Error
We can't rejoin our server even after a full restart. 
Server log says
2020-10-12 15:17 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Placeable_brand_flags/JD.i3d (0.62 ms)
2020-10-12 15:17 d:/servers/service12498/home/games/FarmingSimulator19/mods/MW_PLACEABLE_HOF_USA/SCS_FUELSTATION.i3d (2.15 ms)
2020-10-12 15:17 d:/servers/service12498/home/games/FarmingSimulator19/mods/A_Placeable_Pack/townHall.i3d (13.70 ms)
2020-10-12 15:17 d:/servers/service12498/home/games/FarmingSimulator19/mods/MW_PLACEABLE_HOF_USA/SCS_FARM_HOUSE_A.i3d (292.88 ms)
2020-10-12 15:17 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_GlobalCompanyPlaceable_sawmill/SW_Sawmill.i3d (99.96 ms)
2020-10-12 15:17 dataS2/character/humans/player/player01.i3d (276.51 ms)
2020-10-12 15:17   Setting 'Radio Volume': 0.5
2020-10-12 15:17   Setting 'Vehicle Volume': 0.80000001192093
2020-10-12 15:17   Setting 'Environment Volume': 0.80000001192093
2020-10-12 15:17   Setting 'GUI Volume': 0.5
2020-10-12 15:17   Info: Savegame Setting 'dirtInterval': 4
2020-10-12 15:17   Info: Savegame Setting 'plantGrowthRate': 0
2020-10-12 15:17   Info: Savegame Setting 'fuelUsageLow': false
2020-10-12 15:17   Info: Savegame Setting 'plowingRequiredEnabled': true
2020-10-12 15:17   Info: Savegame Setting 'weedsEnabled': true
2020-10-12 15:17   Info: Savegame Setting 'limeRequired': true
2020-10-12 15:17 John joined the game
2020-10-12 15:18 	### CourseplayMultiplayer: writing 26 courses 
2020-10-12 15:18 	### CourseplayMultiplayer: writing 5 folders 
2020-10-12 15:18 	### CourseplayMultiplayer: writing 1 custom fields 
2020-10-12 15:18 Error: Running LUA method 'packetReceived'.
2020-10-12 15:18 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Courseplay/Events/SiloSelectedFillTypeEvent.lua:98: attempt to index field 'vehicle' (a nil value)
2020-10-12 15:18 Error: Running LUA method 'packetReceived'.
2020-10-12 15:18 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Courseplay/Events/SiloSelectedFillTypeEvent.lua:77: attempt to index field 'vehicle' (a nil value)
2020-10-12 15:18 Error: Running LUA method 'packetReceived'.
2020-10-12 15:18 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Courseplay/Events/SiloSelectedFillTypeEvent.lua:77: attempt to index field 'vehicle' (a nil value)
2020-10-12 15:18 Error: Running LUA method 'packetReceived'.
2020-10-12 15:18 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Courseplay/Events/SiloSelectedFillTypeEvent.lua:77: attempt to index field 'vehicle' (a nil value)
2020-10-12 15:18 Error: Running LUA method 'packetReceived'.
2020-10-12 15:18 d:/servers/service12498/home/games/FarmingSimulator19/mods/FS19_Courseplay/Events/SiloSelectedFillTypeEvent.lua:77: attempt to index field 'vehicle' (a nil value)

### LINKED ISSUE #6263: MP: Arbeitsdauer Anzeige
Wollte nur kurze Frage.
 Im SP kann man sehen wenn Kurse eingestellt ist wie lange der Helfer braucht bis er fertig is mit dem Feldarbeit.. Bei MP zeigt das nicht an wie lang er braucht.. ist das so das er im MP nicht anzeigt nur SP?

LG Chris

### LINKED ISSUE #6308: CP Unloader not responding in MP (v6.02.00076)
We are experiancing an issue were often an unloader is assigned to a harvester but does respond when called. Other players on the server have reported that it works occasionally but not most of the time.

FS19 Version : 1.7.1
CP Version : v6.02.00076
Map : Lawfolds, Aberdeenshire

Client Log : https://pastebin.com/u2N8gtEK
Server Log : https://pastebin.com/f85aCmTs

Process used:

1. Stopped server & changed password to prevent others from joining and keep the logs clean
2. Started server and client fresh
3. Enabled debug modes 4,7,14
4. Placed combine on course and started in 'field work' mode - combine starts harvesting
5. Place tractor (T7.313) with trailer (Joskin) on field, select 'combi mode', select 'Start course at' as 'Unloading', select correct combine from search panel and click Drive Course - tractor waiting
6. Combine fills to 100% but tractor remains unresponsive.

Throughout the log there are no direct error messages but debug mode4 constantly reports.....
CombineUnloadManager: Combine with most fill level is N/A

....and client log reports the following each time the harvester reaches near full or if you manaully select 'Request Driver'
g_combineUnloadManager:getHasUnloaders(vehicle):false

If we are doing something wrong then please advise, if not then I hope this information helps resolve the issue.

### LINKED ISSUE #6317: Fuelling
Hello upon recently if I’m running cp and machine run out of fuel you could drive tanker beside and it would start refuelling but won’t happen now what’s changed?

### LINKED ISSUE #6350: .79 Client Crash during field scan after entering a save
As titled says, updated to .79, attempted to load the save, it starts scanning fields, then the giants client goes not responding, it loads fine with courseplay disabled.

See log.

https://pastebin.com/9Dr498RK

### LINKED ISSUE #6384: MP Error: attempt to index field 'currentHelper' (a nil value)
See below for the English version.

**----------------------------- German version ---------------------------------------------**
Nach einer gewissen Laufzeit kriegen wir auf unserem Server immer einen Fehler, welcher augenscheinlich mit Coursplay zusammen hängt. Zumindest wird Coursplay im LUA call stack erwähnt. (Siehe ErrorLog.txt)

Leider lässt sich der Fehler nicht zuverlässig reproduzieren, da er erst nach einer längeren Laufzeit auftritt. Der Fehler verhindert das Beitreten eines Spielers. Dieser bleibt beim „Synchronisiere Daten mit anderen Spielern“ hängen. Sobald der beitretende Spieler das Synchronisieren abbricht kann auf dem Server normal weitergespielt werden, jedoch kann niemand mehr dem Server beitreten bis ein Neustart gemacht wurde.

Da der Fehler immer erst nach einer gewissen Laufzeit auftritt, habe ich 2 Log Dateien Hochgeladen. Einmal den Log wie der Server startet (RestartLog.txt) und einmal einen Ausschnitt in dem der Fehler auftritt (ErrorLog.txt). Ich hoffe, dass es so etwas  übersichtlicher ist. Bei Bedarf reiche ich das ganze Log nach.

**----------------------------- English version ---------------------------------------------**
After a certain amount of time we always get an error on our server which seems to be related to Coursplay. At least Coursplay is mentioned in the LUA call stack. (See ErrorLog.txt)

Unfortunately, the error cannot be reproduced reliably because it occurs only after a longer runtime. The error prevents a player from joining the game. This player gets stuck during " Synchronize data with other players". As soon as the joining player cancels the synchronization, the players on the server can continue to play normally, but nobody can join the server until a restart is made.

Since the error always occurs after a certain amount of time, I have uploaded 2 log files. One is the log of how the server starts (RestartLog.txt) and the other is a section where the error occurs (ErrorLog.txt). I hope that it is more clearly arrange like this. If necessary I will hand over the whole log.

**----------------------------- Logs ---------------------------------------------**
[RestartLog.txt](https://github.com/Courseplay/courseplay/files/5606839/RestartLog.txt)
[ErrorLog.txt](https://github.com/Courseplay/courseplay/files/5606840/ErrorLog.txt)

### PR DESCRIPTION
**Pull request by schwiti6190**
-fix mode 2/3 in MP
-reduce network load by only sending updated values
-improved mode 9 raycast
-improved baler handling
-diff small changes
-enabled fueling by trailer
-mode 1/4 wait while they get loaded

-closes #6350, closes #6308, closes #6213, closes #6167, closes #5701, closes #6317, closes #6263, closes #6384

### CODE REVIEW

File: AIDriver.lua [hunk 1]
```diff
@@ -201,25 +201,42 @@ end
 
 function AIDriver:writeUpdateStream(streamId, connection, dirtyMask)
 	self.triggerHandler:writeUpdateStream(streamId)
-	streamWriteString(streamId,self.state.name)
-	if self.active then 
+	if self.state ~= self.stateSend then
```
Comment (pvaiko) [inline AIDriver.lua:204]: can we call these stateSent (or lastStateSent) (in past tense) to make it clear what it is

File: BalerAIDriver.lua [hunk 2]
```diff
@@ -34,6 +37,19 @@ function BalerAIDriver:driveFieldwork(dt)
 	return UnloadableFieldworkAIDriver.driveFieldwork(self, dt)
 end
 
+function BalerAIDriver:start(startingPoint)
+	UnloadableFieldworkAIDriver.start(self,startingPoint)
+	--use giants automaticDrop, so we don't have to do it
```
Comment (pvaiko) [inline BalerAIDriver.lua:42]: great!

File: CombineUnloadManager.lua [hunk 3]
```diff
@@ -54,7 +54,7 @@ function CombineUnloadManager:addNewCombines()
 		-- this isn't needed as combines will be added when an CombineAIDriver is created for them
 		-- but we want to be able to reload this file on the fly when developing/troubleshooting
 		for _, vehicle in pairs(g_currentMission.vehicles) do
-			if vehicle.cp.driver and vehicle.cp.driver:is_a(CombineAIDriver) and not self.combines[vehicle] then
+			if vehicle.cp.driver and vehicle.cp.driver.is_a and vehicle.cp.driver:is_a(CombineAIDriver) and not self.combines[vehicle] then
```
Comment (pvaiko) [inline CombineUnloadManager.lua:57]: I remember these errors but still have no idea how can is_a not be defined if there is a driver.

File: FieldworkAIDriver.lua [hunk 4]
```diff
@@ -307,6 +307,13 @@ function FieldworkAIDriver:writeUpdateStream(streamId, connection, dirtyMask)
 		streamWriteIntN(streamId,self.convoyCurrentPosition,5)
 		streamWriteIntN(streamId,self.convoyTotalMembers,5)
 	end
+	if self.fieldworkState and self.fieldworkState ~= self.fieldworkStateSend then
```
Comment (pvaiko) [inline FieldworkAIDriver.lua:310]: Sen**t**

Also wondering if it would make sense to create a wrapper function to set states (instead of directly setting them) and that could also take care of syncing it on MP so there is no need for this check

File: FieldworkAIDriver.lua [hunk 5]
```diff
@@ -491,11 +520,13 @@ function FieldworkAIDriver:driveFieldworkUnloadOrRefill()
 			self.fieldworkUnloadOrRefillState = self.states.WAITING_FOR_UNLOAD_OR_REFILL
 		end
 	elseif self.fieldworkUnloadOrRefillState == self.states.WAITING_FOR_UNLOAD_OR_REFILL then
-		if self:allFillLevelsOk() and not self.heldForUnloadRefill then
-			self:debug('unloaded, continue working')
-			-- not full/empty anymore, maybe because Refilling to a trailer, go back to work
-			self:clearInfoText(self:getFillLevelInfoText())
-			self:changeToFieldwork()
+		if g_updateLoopIndex % 5 == 0 then --small delay, to make sure no more fillLevel change is happening
```
Comment (pvaiko) [inline FieldworkAIDriver.lua:523]: isn't this rather a delay which could be anything between 0 and 4 loops? When it first comes here in loop 35, there'll be no delay.

File: GrainTransportAIDriver.lua [hunk 6]
```diff
@@ -69,7 +69,9 @@ function GrainTransportAIDriver:drive(dt)
 		--checking FillLevels, while loading at StartPoint 
 		if self.readyToLoadManualAtStart then 
 			self:setInfoText('REACHED_OVERLOADING_POINT')
-			self:checkFillUnits()
+			if g_updateLoopIndex % 5 == 0 then
```
Comment (pvaiko) [inline GrainTransportAIDriver.lua:72]: again, if the purpose of this is delay then it may not work as intended

File: OverloaderAIDriver.lua [hunk 7]
```diff
@@ -27,17 +27,20 @@ OverloaderAIDriver.myStates = {
 }
 
 function OverloaderAIDriver:init(vehicle)
+    --there seems to be a bug, where "vehicle" is not always set once start is pressed
+	if vehicle and vehicle:isa(Vehicle) then
+		self:findPipeAndTrailer(vehicle)
+	end
 	CombineUnloadAIDriver.init(self, vehicle)
```
Comment (pvaiko) [inline OverloaderAIDriver.lua:34]: this should set self.vehicle 
still puzzled how this can happen

File: OverloaderAIDriver.lua [hunk 8]
```diff
@@ -27,17 +27,20 @@ OverloaderAIDriver.myStates = {
...
     self.mode = courseplay.MODE_OVERLOADER
-    self.unloadCourseState = self.states.ENROUTE
-    self:findPipeAndTrailer()
+	self.unloadCourseState = self.states.ENROUTE
     self.nearOverloadPoint = false
 end
 
-function OverloaderAIDriver:findPipeAndTrailer()
-    local implementWithPipe = AIDriverUtil.getImplementWithSpecialization(self.vehicle, Pipe)
+function OverloaderAIDriver:findPipeAndTrailer(vehicle)
```
Comment (pvaiko) [inline OverloaderAIDriver.lua:42]: but isn't this only because we call it before CombineUnloadAIDriver.init(self, vehicle), which initializes self.vehicle?

File: OverloaderAIDriver.lua [hunk 9]
```diff
@@ -27,17 +27,20 @@ OverloaderAIDriver.myStates = {
 }
 
 function OverloaderAIDriver:init(vehicle)
+    --there seems to be a bug, where "vehicle" is not always set once start is pressed
+	if vehicle and vehicle:isa(Vehicle) then
```
Comment (pvaiko) [inline OverloaderAIDriver.lua:31]: I don't get this, if I self.vehicle is not set, nothing is going to work. Where do we set self.vehicle? or vehicle is not a vehicle when this is first called?

File: TriggerHandler.lua [hunk 10]
```diff
@@ -178,10 +176,27 @@ function TriggerHandler:onContinue()
 end
 
 function TriggerHandler:writeUpdateStream(streamId)
-	streamWriteString(streamId,self.loadingState.name)
+	if self.loadingState ~= self.loadingStateSend then
```
Comment (pvaiko) [inline TriggerHandler.lua:179]: t

File: UnloadableFieldworkAIDriver.lua [hunk 11]
```diff
@@ -146,61 +146,33 @@ function UnloadableFieldworkAIDriver:isWaitingForUnload()
...
-
---- Check fill levels in all tools and stop when one of them isn't ok
-function UnloadableFieldworkAIDriver:fillLevelsOk(workTool)
-	if workTool.getFillUnits then
-		for index, fillUnit in pairs(workTool:getFillUnits()) do
-			-- let's see if we can get by this abstraction for all kinds of tools
-			local ok = self:isLevelOk(workTool, index, fillUnit)
-			if not ok then
+function UnloadableFieldworkAIDriver:areFillLevelsOk(fillLevelInfo)	
+	for fillType, info in pairs(fillLevelInfo) do
```
Comment (pvaiko) [inline UnloadableFieldworkAIDriver.lua:150]: nice, I always wanted to do this...

**Review by pvaiko — CHANGES_REQUESTED** [review]

File: CombineUnloadManager.lua (hunk 3 above)
Comment (schwiti6190) [reply CombineUnloadManager.lua:57]: might have something to do with this one :
 `status,driver,err,errDriverName = xpcall(AIDriver, function(err) printCallstack(); return self,err,"AIDriver" end, vehicle)`

Comment (schwiti6190) [reply CombineUnloadManager.lua:57]: in `courseplay:setAIDriver(vehicle, mode)`

File: OverloaderAIDriver.lua (hunk 8 above)
Comment (schwiti6190) [reply OverloaderAIDriver.lua:42]: `findPipeAndTrailer()` has to be called before  `OverloaderAIDriver:setHudContent()` so `courseplay.hud:setOverloaderAIDriverContent(self.vehicle)` can be called
